groups:
  - name: example_alert_rules
    rules:
      - alert: TargetDown
        expr: probe_success == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Target {{ $labels.instance }} is down"
          description: "The target {{ $labels.instance }} has been down for more than 5 minutes."