version: '3'

networks:
  monitoring:
    # external: true

services:
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    command: --log.level=debug --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alert_template.tmpl:/etc/alertmanager/alert_template.tmpl
    ports:
      - "9093:9093"
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9091:9090"
    networks:
      - monitoring
    restart: unless-stopped

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - "9115:9115"
    networks:
      - monitoring
    restart: unless-stopped