version: '3.0'

services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
      # - 8096:8096 # jellyfin http
      - 8920:8920 # jellyfin https
      #- "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/jellyfin.conf:/etc/nginx/conf.d/jellyfin.conf:ro
      - ${NGINX_DATA_DIR}/passwd:/opt/passwd:ro
      - ${HTML_DATA_DIR}:/usr/share/nginx/html
      - ../certs:/etc/nginx/ssl
    networks:
      - omv-net
    # depends_on:
    #   - seafile
    restart: unless-stopped

  # gogs:
  #   image: gogs/gogs
  #   ports:
  #     - "10080:3000"
  #   volumes:
  #     - ./data/gogs:/data

  # syncthing:
  #   image: syncthing/syncthing
  #   ports:
  #     - 8384:8384
  #     - 22000:22000
  #   volumes:
  #   - ./data/syncthing:/var/syncthing:rw
  #   networks:
  #     - omv-net
  #   restart: unless-stopped

  db:
    image: mariadb:10.6
    # ports:
    #   - 127.0.0.1:3306:3306
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ${DB_DATA_DIR}:/var/lib/mysql:rw  # Requested, specifies the path to MySQL data persistent store.  
    networks:
      - omv-net
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.16.2
    user: 1000:0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 2g
    volumes:
      -  ${ES_DATA_DIR}:/usr/share/elasticsearch/data  # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - omv-net
    restart: unless-stopped

  memcached:
    image: memcached:1.6.18
    entrypoint: memcached -m 256
    networks:
      - omv-net
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:RELEASE.2024-10-13T13-34-11Z
    volumes:
      - ${data1}:/data1
      - ${data2}:/data2
      - ${data3}:/data3
      - ${data4}:/data4
    ports:
      - "127.0.0.1:${MINIO_PORT}:9000"
      # - "9001:9001"
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" http://minio/data{1...4}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - omv-net
    restart: unless-stopped

  seafile:
    image: docker.seafile.top/seafileltd/seafile-pro-mc:9.0.16 #seafileltd/seafile-mc:latest  切回就是社区版，没有人数限制，可以关闭elasticsearch
    ports:
      - ${SEAFILE_SERVER_PORT_HTTP}:80
      - ${SEAFILE_SERVER_PORT_HTTPS}:443
    volumes:
      - ${SEAFILE_DATA_DIR}:/shared:rw
      - ../certs:/shared/ssl:ro
      - ./seafile/seafile.nginx.conf.template:/templates/seafile.nginx.conf.template:ro
    # 以下只有需要fuse映射才配置，并且需要源系统支持/dev/fuse
    # devices:
    #   - "/dev/fuse:/dev/fuse"
    # cap_add:
    #   - SYS_ADMIN
    # security_opt:
    #   - apparmor:unconfined
    environment:
      - DB_HOST=db
      - TIME_ZONE=Etc/UTC  # Optional, default is UTC. Should be uncomment and set to your local time zone.    
      - DB_ROOT_PASSWD
      - SEAFILE_ADMIN_EMAIL
      - SEAFILE_ADMIN_PASSWORD
      - SEAFILE_SERVER_LETSENCRYPT
      - SEAFILE_SERVER_HOSTNAME
    depends_on:
      - db
      - memcached
      - elasticsearch
      - minio
    networks:
      - omv-net
    restart: unless-stopped

  aria2:
    image: superng6/aria2
    environment:
      - PUID=1000
      - PGID=1000
      #- TZ=Asia/Shanghai
      - SECRET=vNp5keQn4YWmM
    volumes:
      - ${ARIA2_DATA_DIR}/config:/config
      - ${HTML_DATA_DIR}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6800:6800
    restart: unless-stopped

  ariang:
    image: superng6/ariang:latest
    ports:
      - 8080:80

  jellyfin:
    image: jellyfin/jellyfin:10.10.3
    runtime: nvidia # Expose NVIDIA GPUs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    user: 1000:1000
    group_add:
      - "148" # getent group render | cut -d: -f3
      - "44" # getent group video | cut -d: -f3
    # devices:
    #   - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    #   # - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    volumes:
      - ${JELLYFIN_DATA_DIR}/config:/config # Configuration directory
      - ${JELLYFIN_DATA_DIR}/cache:/cache # Cache directory
      - ${JELLYFIN_MEDIA_DIR}:/media:shared   # support s3fs
    ports:
      - 8096:8096 # api port
      # - 8920:8920 # admin port
    # restart: unless-stopped
networks:
  omv-net:
    name: omv-net
